What analyses do I want to do?

- How 'similar' is our subset to the overall sample in terms of demographics and outcome variables?

Wouldn't it be cool if I could generatively create a story for what "happened" to a particular participant based on the underlying statistical properties of the data?

In [36]:
import polars as pl
import seaborn as sns

In [3]:
DATA_FOLDER = "../data/processed"
data_lazy = pl.scan_parquet(f"{DATA_FOLDER}/index_data.parquet")

In [ ]:
data_lazy

In [5]:
data = data_lazy.collect()

In [26]:
data.head()

shape: (5, 80)
┌────────────┬────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ unique_id  ┆ sex    ┆ race       ┆ age       ┆ … ┆ is_wages_ ┆ has_occup ┆ has_indus ┆ has_wages │
│ ---        ┆ ---    ┆ ---        ┆ ---       ┆   ┆ mean_incr ┆ ational_o ┆ try_outco ┆ _outcomes │
│ str        ┆ str    ┆ str        ┆ str       ┆   ┆ eased     ┆ utcomes   ┆ mes       ┆ ---       │
│            ┆        ┆            ┆           ┆   ┆ ---       ┆ ---       ┆ ---       ┆ bool      │
│            ┆        ┆            ┆           ┆   ┆ bool      ┆ bool      ┆ bool      ┆           │
╞════════════╪════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ FDFac9aUDd ┆ Male   ┆ White (not ┆ 45 to 54  ┆ … ┆ true      ┆ false     ┆ true      ┆ true      │
│ US         ┆        ┆ Hispanic)  ┆ years     ┆   ┆           ┆           ┆           ┆           │
│ AU04D9DcDa ┆ Female ┆ Black (not ┆ 55 to 64  ┆ … ┆ true      ┆ false     ┆ true      ┆ true      │
│ Lc         ┆        ┆ Hispanic)  ┆ years     ┆   ┆           ┆           ┆           ┆           │
│ 0U9b5b5UaF ┆ Female ┆ White (not ┆ 17 to 24  ┆ … ┆ true      ┆ false     ┆ true      ┆ true      │
│ FU         ┆        ┆ Hispanic)  ┆ years     ┆   ┆           ┆           ┆           ┆           │
│ 2D1563FF0F ┆ Male   ┆ White (not ┆ 55 to 64  ┆ … ┆ false     ┆ false     ┆ true      ┆ true      │
│ A8FA3D2E85 ┆        ┆ Hispanic)  ┆ years     ┆   ┆           ┆           ┆           ┆           │
│ 59C524F2E1 ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆        ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ cafdfAUU9A ┆ Male   ┆ White (not ┆ 35 to 44  ┆ … ┆ false     ┆ false     ┆ true      ┆ true      │
│ 95         ┆        ┆ Hispanic)  ┆ years     ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [27]:
(
    data
    .filter(
        pl.col("has_occupational_outcomes"),
    )
    .group_by(
        pl.col("is_wages_mean_increased"),
    )
    .len()
)

shape: (2, 2)
┌─────────────────────────┬────────┐
│ is_wages_mean_increased ┆ len    │
│ ---                     ┆ ---    │
│ bool                    ┆ u32    │
╞═════════════════════════╪════════╡
│ true                    ┆ 101192 │
│ false                   ┆ 60439  │
└─────────────────────────┴────────┘

In [30]:
101192 / (101192 + 60439)

0.6260680191299937

In [28]:
(
    data
    .group_by(
        pl.col("is_wages_mean_increased"),
    )
    .len()
)

shape: (2, 2)
┌─────────────────────────┬─────────┐
│ is_wages_mean_increased ┆ len     │
│ ---                     ┆ ---     │
│ bool                    ┆ u32     │
╞═════════════════════════╪═════════╡
│ false                   ┆ 6864771 │
│ true                    ┆ 5862018 │
└─────────────────────────┴─────────┘

In [29]:
5862018 / (5862018 + 6864771)

0.4606046348375855

In [47]:
participation_durations = (
    data.select(
        (pl.col("exit_date") - pl.col("entry_date")).alias("participation_duration")
    )
    .filter(
        (pl.col("participation_duration") > 0) & ~(pl.col("participation_duration").is_null())
    )
)

In [ ]:
sns.histplot(data=participation_durations.to_numpy().reshape(1, -1)[0])