In [12]:
import pandas as pd
from datacommons_client.client import DataCommonsClient

In [13]:
client = DataCommonsClient(dc_instance="datacommons.one.org")

In [9]:
df = pd.read_excel("../data/raw/WCM_StateDashboard_2023All_Regions_All_States.xlsx", skiprows=8)

In [10]:
df = df.rename(
    columns={
        "Program Year": "program_year",
        "Region": "region",
        "State/Territory": "state",
        "ETA Code": "eta_code",
        "Local Board Name": "local_board_name",
        "Jurisdiction Name": "jurisdiction_name",
        "Created Timestamp": "created_timestamp",
        "Modified Timestamp": "modified_timestamp",
        "Status": "status"
    }
)

In [16]:
df['jurisdiction_state'] = df.apply(lambda x : x["jurisdiction_name"] + ', ' + x["state"] , axis=1)

In [27]:
county_names = df['jurisdiction_state'].unique()

In [ ]:
# Fetch the corresponding DCIDs for the juristictions
counties = client.resolve.fetch_dcids_by_name(county_names).to_flat_dict()

In [35]:
# Extract just the DCIDs
county_dcids = [counties[county_name] for county_name in county_names if isinstance(counties[county_name], str)]

In [39]:
len(county_dcids)

3872

In [36]:
df_county = client.observations_dataframe(entity_dcids=county_dcids, variable_dcids=['Count_Person', 'Median_Age_Person', 'Median_Income_Person'], date='latest')

In [37]:
df_county

,date,entity,entity_name,variable,variable_name,facetId,importName,measurementMethod,observationPeriod,provenanceUrl,unit,value
0,2024,geoId/28095,Monroe County,Count_Person,Total population,2176550201,USCensusPEP_Annual_Population,CensusPEPSurvey,P1Y,https://www.census.gov/programs-surveys/popest...,None,33483.0
1,2023,geoId/28095,Monroe County,Count_Person,Total population,1145703171,CensusACS5YearSurvey,CensusACS5yrSurvey,None,https://www.census.gov/programs-surveys/acs/da...,None,33928.0
2,2020,geoId/28095,Monroe County,Count_Person,Total population,1541763368,USDecennialCensus_RedistrictingRelease,USDecennialCensus,None,https://www.census.gov/programs-surveys/decenn...,None,34180.0
3,2024,geoId/28095,Monroe County,Count_Person,Total population,2390551605,USCensusPEP_AgeSexRaceHispanicOrigin,CensusPEPSurvey_Race2000Onwards,P1Y,https://www2.census.gov/programs-surveys/popes...,None,33483.0
4,2023,geoId/28095,Monroe County,Count_Person,Total population,1964317807,CensusACS5YearSurvey_SubjectTables_S0101,CensusACS5yrSurveySubjectTable,None,https://data.census.gov/table?q=S0101:+Age+and...,None,33928.0
...,...,...,...,...,...,...,...,...,...,...,...,...
42719,2023,geoId/48065,Carson County,Median_Income_Person,Median Income of a Population,3214767095,CensusACS5YearSurvey_SubjectTables_S0701,CensusACS5yrSurveySubjectTable,None,https://data.census.gov/cedsci/table?q=S0701&t...,USDollar,42308.0
42720,2023,geoId/53057,Skagit County,Median_Income_Person,Median Income of a Population,1305418269,CensusACS5YearSurvey,CensusACS5yrSurvey,None,https://www.census.gov/programs-surveys/acs/da...,USDollar,42170.0
42721,2023,geoId/53057,Skagit County,Median_Income_Person,Median Income of a Population,3214767095,CensusACS5YearSurvey_SubjectTables_S0701,CensusACS5yrSurveySubjectTable,None,https://data.census.gov/cedsci/table?q=S0701&t...,USDollar,42170.0
42722,2023,geoId/13121,Fulton County,Median_Income_Person,Median Income of a Population,1305418269,CensusACS5YearSurvey,CensusACS5yrSurvey,None,https://www.census.gov/programs-surveys/acs/da...,USDollar,50463.0
42723,2023,geoId/13121,Fulton County,Median_Income_Person,Median Income of a Population,3214767095,CensusACS5YearSurvey_SubjectTables_S0701,CensusACS5yrSurveySubjectTable,None,https://data.census.gov/cedsci/table?q=S0701&t...,USDollar,50463.0

In [24]:
df_county[df_county["variable"] == "Median_Income_Person"]

,date,entity,entity_name,variable,variable_name,facetId,importName,measurementMethod,observationPeriod,provenanceUrl,unit,value
64,2023,geoId/01117,Shelby County,Median_Income_Person,Median Income of a Population,1305418269,CensusACS5YearSurvey,CensusACS5yrSurvey,None,https://www.census.gov/programs-surveys/acs/da...,USDollar,46566.0
65,2023,geoId/01117,Shelby County,Median_Income_Person,Median Income of a Population,3214767095,CensusACS5YearSurvey_SubjectTables_S0701,CensusACS5yrSurveySubjectTable,None,https://data.census.gov/cedsci/table?q=S0701&t...,USDollar,46566.0
66,2023,geoId/01073,Jefferson County,Median_Income_Person,Median Income of a Population,1305418269,CensusACS5YearSurvey,CensusACS5yrSurvey,None,https://www.census.gov/programs-surveys/acs/da...,USDollar,35600.0
67,2023,geoId/01073,Jefferson County,Median_Income_Person,Median Income of a Population,3214767095,CensusACS5YearSurvey_SubjectTables_S0701,CensusACS5yrSurveySubjectTable,None,https://data.census.gov/cedsci/table?q=S0701&t...,USDollar,35600.0
68,2023,geoId/01127,Walker County,Median_Income_Person,Median Income of a Population,1305418269,CensusACS5YearSurvey,CensusACS5yrSurvey,None,https://www.census.gov/programs-surveys/acs/da...,USDollar,29524.0
69,2023,geoId/01127,Walker County,Median_Income_Person,Median Income of a Population,3214767095,CensusACS5YearSurvey_SubjectTables_S0701,CensusACS5yrSurveySubjectTable,None,https://data.census.gov/cedsci/table?q=S0701&t...,USDollar,29524.0
70,2023,geoId/01021,Chilton County,Median_Income_Person,Median Income of a Population,1305418269,CensusACS5YearSurvey,CensusACS5yrSurvey,None,https://www.census.gov/programs-surveys/acs/da...,USDollar,31816.0
71,2023,geoId/01021,Chilton County,Median_Income_Person,Median Income of a Population,3214767095,CensusACS5YearSurvey_SubjectTables_S0701,CensusACS5yrSurveySubjectTable,None,https://data.census.gov/cedsci/table?q=S0701&t...,USDollar,31816.0
72,2023,geoId/01115,St. Clair County,Median_Income_Person,Median Income of a Population,1305418269,CensusACS5YearSurvey,CensusACS5yrSurvey,None,https://www.census.gov/programs-surveys/acs/da...,USDollar,37446.0
73,2023,geoId/01115,St. Clair County,Median_Income_Person,Median Income of a Population,3214767095,CensusACS5YearSurvey_SubjectTables_S0701,CensusACS5yrSurveySubjectTable,None,https://data.census.gov/cedsci/table?q=S0701&t...,USDollar,37446.0
74,2023,geoId/01009,Blount County,Median_Income_Person,Median Income of a Population,1305418269,CensusACS5YearSurvey,CensusACS5yrSurvey,None,https://www.census.gov/programs-surveys/acs/da...,USDollar,31174.0
75,2023,geoId/01009,Blount County,Median_Income_Person,Median Income of a Population,3214767095,CensusACS5YearSurvey_SubjectTables_S0701,CensusACS5yrSurveySubjectTable,None,https://data.census.gov/cedsci/table?q=S0701&t...,USDollar,31174.0

In [ ]:
df.to_csv("data/processed/workforce_boards.csv")